# Generated by Django 3.2.20 on 2023-08-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('subject', models.CharField(choices=[('feedback', 'Feedback'), ('general', 'General'), ('subscriptions', 'Subscriptions'), ('reclamation', 'Reclamation')], max_length=150)),
                ('message', models.TextField(max_length=700, verbose_name='Your message')),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
    ]
