# Generated by Django 3.2.20 on 2023-08-09 06:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('featured_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('hours', models.IntegerField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('equipment_included', models.BooleanField(default=False)),
                ('cleaning_product_included', models.BooleanField(default=False)),
                ('deferrable_hours', models.BooleanField(default=False)),
                ('minimum_duration', models.IntegerField()),
                ('minimum_time_cancelation', models.IntegerField()),
            ],
            options={
                'ordering': ['hours'],
            },
        ),
    ]
