# Generated by Django 3.2.20 on 2023-08-02 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('done', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('GARDENING', 'Gardening'), ('CLEANING', 'Cleaning'), ('GARDEN_PATCH', 'Garden patch'), ('SWIMMING_POOL', 'Swimming pool'), ('INSTALLATION_AND_REPAIR', 'Renovation and repair'), ('HOME_CARE', 'Home care')], default='CLEANING', max_length=50)),
                ('repeat', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='tasks.employee')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
