# Generated by Django 3.2.20 on 2023-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_due_date'),
        ('appointments', '0002_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
